### ISSUE TITLE
Issue with argTypes

### ISSUE THREAD

**Issue by mbulfair** [break-stuff/wc-storybook-helpers#13]
Working with stencil 4.4.1
Storybook 7.4.6
wc-helpers: 1.0.6

I have a basic stencil component, everything worked fine in v1.0.3
When upgrading to 1.0.6 I noticed in this example all the args, were not being passed to the component story. 
After changing to use typescript I noticed:

![image](https://github.com/break-stuff/wc-storybook-helpers/assets/5325543/5105eba3-fbcb-463a-b1fb-d6b686e07026)

I've reviewed all the docs however I can't seem to find what's wrong.

**Comment by certainlyakey** [comment]
Same here. Set up a 4.4.0 project from scratch with wc-storybook-helpers 1.0.6 and Storybook 7.4.6 (tried to upgrade to 7.5.0 as well), couldn't make the default values of the args actually to appear in the preview frame. The arg types in the Controls panel do appear fine. 

I followed this repo as an example https://github.com/break-stuff/stencil-storybook-demo. It is working there if you just clone it and do an `npm install` and then `npm run dev`. I tried to bring as much stuff from that repo to my example, but still couldn't find what exactly is the difference.

**Comment by break-stuff** [comment]
Thank you! I'm digging into it now.

**Comment by break-stuff** [comment]
I think I found the issue. It looks like there may be a bug in the CEM/Analyzer for Stencil. Other frameworks add an `attribute` property to the component `members` with the name of the HTML attribute. Stencil's implementation doesn't appear to be doing that. I should be able to patch it in the helpers for now.

**Comment by break-stuff** [comment]
A patch was deployed in 1.0.7 (#14). Let me know if you run into any issues.

**Comment by herrKlein** [comment]
I sadly still have the same issue.
I think it's only a typing error, so I fixed it like this: 
```js
  argTypes: argTypes as ArgTypes<Args>, // <- explicitly set the type of argTypes
```

**Comment by break-stuff** [comment]
If you update the type to `const meta: Meta<MyElement> = {`, does that fix the type for you?Get Outlook for Android

**Comment by break-stuff** [comment]
@herrKlein I just wanted to follow up and see if updating the type in my comment above helped?

**Comment by break-stuff** [comment]
I will close this for now. Let me know if you run into this issue again.

**Comment by certainlyakey** [comment]
With 1.0.7, issue is no more there for me.

**Comment by herrKlein** [comment]
Yes works! thanks

**Comment by break-stuff** [comment]
Thank you! I also pushed out 1.0.9 last night with some more improvements that should help provide better `argTypes` and default values.
