### ISSUE TITLE
`Number` prop is shown with a `text` control

### ISSUE THREAD

**Issue by pruik** [break-stuff/wc-storybook-helpers#15]
It looks like the `argTypes` returned by the `getWcStorybookHelpers` method doesn't read number types correctly. We'll have a look with our team to see if we can find a solution and/or open a PR later today :) 

**Lit component src**
![image](https://github.com/break-stuff/wc-storybook-helpers/assets/788083/5ccf3023-7800-48b4-83b2-1ed8f2c466fb)

**As shown in storybook**
(note the 'Edit string...' placeholder in the control)
![image](https://github.com/break-stuff/wc-storybook-helpers/assets/788083/1a3a17f8-8dc0-4201-9244-f71551b1de23)

**`console.log` of the argTypes**
![image](https://github.com/break-stuff/wc-storybook-helpers/assets/788083/fd947669-64b9-48ae-b74a-17596138f6f4)

**Comment by pruik** [comment]
I think I found the bug, it's on line 243 (and 247) of `cem-utilities.ts`. It requires a string to be equal or less than 2 characters, which will never happen :)

![image](https://github.com/break-stuff/wc-storybook-helpers/assets/788083/6e3a291d-9d92-4817-b6bc-d79277f9813c)

(I'm unable to create a branch to open a PR, so I figured I would do it this way)

**Comment by break-stuff** [comment]
Thank you! Someone else had pointed that out to me as well. I have a fix for that coming soon.

**Comment by break-stuff** [comment]
Release 1.0.8 (#17) was just deployed and should fix this issue.

**Comment by pruik** [comment]
Yes, it works perfectly. Thanks!

**Comment by break-stuff** [comment]
Awesome! Thank you! I just pushed out 1.0.9 with some more adjustments, that may be helpful too.

**Comment by certainlyakey** [comment]
Thanks for resolving this! I was about to report it as well but then saw the new release ☺️
