### ISSUE TITLE
Named slots are always wrapped in a `span` element

### ISSUE THREAD

**Issue by pruik** [break-stuff/wc-storybook-helpers#16]
One of the components we list in our storybook has a named slot that can be used to place buttons in the footer. We expect developers to place separate buttons in the slot like this:

<kbd>![image](https://github.com/break-stuff/wc-storybook-helpers/assets/788083/30048ec8-57cc-4668-b40c-f00b89ad3ff3)</kbd>

That way, we can apply some styling on the `<slot>` container element that automatically applies a small `gap` between each button.

Unfortunately, the `template` method from `getWcStorybookHelpers` always wraps a `<span slot="footer">` element around the `footer-slot` args. This means that the `gap` from the slot-styling is not applied to the buttons, and the buttons show incorrectly in storybook:

<kbd>![image](https://github.com/break-stuff/wc-storybook-helpers/assets/788083/c90646ab-67c8-4598-8a42-75c824414cb1)</kbd>

**Request**
We would like an option to apply the `slot="footer"` attribute to every element in the `footer-slot`, instead of wrapping it in a `<span>`. We'll have a look with our team if we can find a solution and/or open a PR later today :)

P.S.
We could also change our story to add `<uc-button slot="footer" />` to the `default-slot`, but we already use this default slot for other content.

**Comment by break-stuff** [comment]
I will look into this. In the meantime, you can use the template to pass slots in, if you need to.

https://www.npmjs.com/package/wc-storybook-helpers#templates

**Comment by break-stuff** [comment]
I've been thinking about this and if you need to add named slots on something other than a span, you should be able to add them to the default slot control with the slot name on it.

**Comment by break-stuff** [comment]
Closing for now. If these options don't work for you, please let me know.
