### ISSUE TITLE
Failed to execute 'observe' on 'MutationObserver'

### ISSUE THREAD

**Issue by pruik** [break-stuff/wc-storybook-helpers#19]
We tried out version 1.0.8 that fixes the number control (Thanks for the quick fix, btw :D )
Unfortunately, we noticed a breaking error in one of our components, originating from line 211 in `html-templates.ts`:

<kbd>![image](https://github.com/break-stuff/wc-storybook-helpers/assets/788083/a05e59a5-3fb3-4f5f-bcdc-143b3dfe9ef8)</kbd>

**Comment by break-stuff** [comment]
I will take a look. There were some improvements in 1.0.9. does that fix your issue?

**Comment by break-stuff** [comment]
Ah, I think I see your issue. I added some docs for this in the latest release.

https://www.npmjs.com/package/wc-storybook-helpers#troubleshooting-templates

**Comment by pruik** [comment]
Sorry, I didn't mention it but 1.0.9 also had the same issue (And a stray console.log ;) )

**Comment by pruik** [comment]
Hmm, this would mean that each `getter` needs a setter in the code, which is just not feasible.

Additionally, it breaks the `@query` decorator from lit, since this generates a getter method:
```@query("dialog") $dialog!: HTMLDialogElement;```

**Comment by break-stuff** [comment]
Ah this is a really good call-out. Thank you! Let me take a look.

**Comment by break-stuff** [comment]
I think I have a solution. I will work on getting out today or tomorrow.

**Comment by break-stuff** [comment]
This should be fixed in release 1.0.10 (#20). Let me know if you run into any issues.

**Comment by pruik** [comment]
Works like a charm, thanks! :+1:
