### ISSUE TITLE
Long list of icons not showing a select list

### ISSUE THREAD

**Issue by pruik** [break-stuff/wc-storybook-helpers#23]
The latest version of the storybook-helpers (1.0.10) unfortunately brought in a new bug.

We have an `icon` property on a component that can take one of a long list of possible values (over 300 values).

We noticed that version 1.0.10 no longer showed a dropdown list for this property, and after some experimentation we noticed that the control in storybook would change when we removed some of the icons. Some more digging revealed that one of the possible icon values is `format_list_numbered`, which contains the `number` string, so then storybook would render a Number control. Removing this icon value from the list of values would show us a Date control, because another icon value is `system_update`, which contains `date`.

I would suggest doing the check in `cem-utilities:260` for the Select control at the start of the `getControl` method :)

**Comment by pruik** [comment]
Hmm, simply moving it up would always show a selector if the type is something like `number | undefined`.
Perhaps the types should be:
- `.split("|")` first
- remove `undefined` from that array (and maybe `null`?)
- check the first item of the resulting array, whether it is `date`, `number`, etc.
- if no type is found
  - use selector if there are multiple items in the list
  - use `text` otherwise

**Comment by break-stuff** [comment]
Ah, this makes sense. Let me take a look.Get Outlook for Android

**Comment by break-stuff** [comment]
I just deployed release 1.1.1 (#24) which should fix your problem. Let me know if you run into any issues.

**Comment by pruik** [comment]
Yess, that works perfectly. Thanks again :D
