### ISSUE TITLE
Move CSS Vars From Inline Styles to Style Block

### ISSUE THREAD

**Issue by break-stuff** [break-stuff/wc-storybook-helpers#40]
The goal is to make the component more readable by moving the CSS variable declarations off of the inline `styles` attribute and into a style tag.

Now:
```html
<my-element styles="--my-var-1: value; --my-var-2: value; --my-var-3: value;"></my-element>
```

Goal:
```html
<style>
  my-element {
    --my-var-1: value;
    --my-var-2: value;
    --my-var-3: value;
  }
</style>
<my-element></my-element>
```

  - This would be the same style tag used by the CSS parts
  - The style tag would only display if there are parts or variables
  - Variables will only display if they differ from the default value

**Comment by rstoneIDBS** [comment]
"Variables will only display if they differ from the default value" - curious as to how this can be achieved? (suspecting this is a cut/copy/paste from another issue)

**Comment by break-stuff** [comment]
The custom elements manifest has the default value, so we can compare that to the control's value and omit it if they are the same.
