### ISSUE TITLE
Importing setWcStorybookHelpersConfig

### ISSUE THREAD

**Issue by binlabs** [break-stuff/wc-storybook-helpers#5]
I found a minor issue, but I also found a workaround.

The [Configuration section of the README](https://github.com/break-stuff/wc-storybook-helpers#configuration) shows how the package exposes a method for configuration:
```js
//preview.js
import { setWcStorybookHelpersConfig } from "wc-storybook-helpers";

setWcStorybookHelpersConfig({ ... });
setCustomElementsManifest(customElements);
```

But I can't seem to import it from the package's root. I'm only able to get it imported from the dist directory:
```ts
import { setWcStorybookHelpersConfig } from 'wc-storybook-helpers/dist/storybook-utils';
```

I think there may just be a missing export [here in the index declaration file](https://github.com/break-stuff/wc-storybook-helpers/blob/main/index.d.ts)?

Thanks again for work, it's a big help.

**Comment by break-stuff** [comment]
Perfect! Thank you! I have fixed it in #7 and deployed the fix.
