### ISSUE TITLE
Multiple versions of Lit loaded

### ISSUE THREAD

**Issue by gambolputty** [break-stuff/wc-storybook-helpers#54]
Hello! Thanks for creating this package :)

I have the recent version of Lit installed. After installing `wc-storybook-helpers`, Lit complains in the dev console that multiple versions are loaded. 

![Bildschirmfoto 2024-02-27 um 15 52 21](https://github.com/break-stuff/wc-storybook-helpers/assets/8270488/f79894ad-b6ea-4855-b6f6-9b2ab7b67a2f)

I found that this package ships it's own ( at the moment outdated) versions of `lit-html`, `lit-element`, `@lit/reactive-element`.

Is it possible to make Lit a peer dependency and load my existing installation of it?

```bash
➜  vite-lit-play git:(main) ✗ npm ls @lit/reactive-element
vite-lit-play@0.0.0 /Users/gregor/Git/vite-lit-play
├─┬ lit@3.1.2
│ ├── @lit/reactive-element@2.0.4
│ └─┬ lit-element@4.0.4
│   └── @lit/reactive-element@2.0.4 deduped
└─┬ wc-storybook-helpers@1.4.1
  └─┬ lit@2.8.0
    ├── @lit/reactive-element@1.6.3
    └─┬ lit-element@3.3.3
      └── @lit/reactive-element@1.6.3 deduped

➜  vite-lit-play git:(main) ✗ npm ls lit-html
vite-lit-play@0.0.0 /Users/gregor/Git/vite-lit-play
├─┬ lit@3.1.2
│ ├─┬ lit-element@4.0.4
│ │ └── lit-html@3.1.2 deduped
│ └── lit-html@3.1.2
└─┬ wc-storybook-helpers@1.4.1
  └─┬ lit@2.8.0
    ├─┬ lit-element@3.3.3
    │ └── lit-html@2.8.0 deduped
    └── lit-html@2.8.0

➜  vite-lit-play git:(main) ✗ npm ls lit-element
vite-lit-play@0.0.0 /Users/gregor/Git/vite-lit-play
├─┬ lit@3.1.2
│ └── lit-element@4.0.4
└─┬ wc-storybook-helpers@1.4.1
  └─┬ lit@2.8.0
    └── lit-element@3.3.3
```

**Comment by break-stuff** [comment]
Yeah, I think that's reasonable. I just deployed that change in v1.5.0. Let me know if you run into any issues.

**Comment by rstoneIDBS** [comment]
See my comment on the other issue, introducing a peer dependency on an 'older' version of lit causes npm install issues with newer (3.x) versions :( Looking at the npm documentation, I'm not sure how this can be fixed either.

**Comment by certainlyakey** [comment]
On 1.5.1, i get this error in browser console for every story that imports lit after building Storybook for prod: 

```
Original error message: Error: page.evaluate: TypeError: Cannot read properties of undefined (reading 'toString')
```

If I switch back to 1.4.0, the error goes away.

We use Stencil, so we don't need lit outside of using it with wc-storybook-helpers, and I suppose any lit version goes for us. However the error appears whether i use the `overrides` workaround of @rstoneIDBS or simply drop the lit version compatible with this package (`^2.6.1`) to `devDependencies`.

**Comment by break-stuff** [comment]
Thank you! Release 1.5.2 should fix that so you don't need to provide overrides. Let me know if you see any issues.

**Comment by gambolputty** [comment]
@break-stuff Fantastic! It's working very well on my side so far. Should I encounter any issues I'll come back to this issue.

Thank you very much for taking care and solving this so quickly! 💚

**Comment by break-stuff** [comment]
Thank you for contributing!

**Comment by rstoneIDBS** [comment]
Thanks @break-stuff , that fixes it for me too
