### ISSUE TITLE
Slot default content doesn't get rendered

### ISSUE THREAD

**Issue by stevenkuster** [break-stuff/wc-storybook-helpers#61]
When I add default content to a slot in a component it doesn't get rendered because `storybook-helpers` renders some hidden stuff into the slot.

For example, I have a modal component which has a default slot that looks like this:
``` js
return html`<slot>${msg("Are you sure?")}</slot>`;
```

However, if I have a look at the component in Storybook the content doesn't get rendered. In the image below you see that between the lines there is no default `Are you sure?` text.
<img width="501" alt="Screenshot 2024-03-27 at 10 10 37" src="https://github.com/break-stuff/wc-storybook-helpers/assets/1954635/1c5e13f1-48de-4e18-8d5c-c0bf53cf4ff1">

When I recreate that same story in Storybook without the use of `storybook-helpers` the text gets rendered just fine.
<img width="506" alt="Screenshot 2024-03-27 at 10 12 50" src="https://github.com/break-stuff/wc-storybook-helpers/assets/1954635/0b18b39d-e8d6-4ce8-ac67-30bc203d3db5">

**Comment by break-stuff** [comment]
This should be fixed with the latest merge. I will deploy it early this week.

**Comment by stevenkuster** [comment]
Awesome, thanks a lot. I'll give it a try when the new release is available. 🙌
