### ISSUE TITLE
camelCase args create lowercase copies and make controls not work

### ISSUE THREAD

**Issue by nikita-rudenko** [break-stuff/wc-storybook-helpers#68]
I have the following in my LitElement component:

```
@property({ type: Boolean })
isDisabled: boolean = false;

@property({ type: Boolean })
isLoading: boolean = false;
```

Using `[wc-storybook-helpers](https://github.com/break-stuff/wc-storybook-helpers)`, it appears correctly in the UI:

![image](https://github.com/break-stuff/wc-storybook-helpers/assets/36961943/20459779-6b0e-46df-96d1-9bcdaa24c1b6)

However, when I change the value, Storybook is trying to change values for `isdisabled` and `isloading` too. That ends up in the following shape of `args`:

```
{
  isLoading: true,
  isDisabled: false,
  isloading: null,
  isdisabled: null
}
```

And basically any change Storybook controls for these props does nothing. I guess lowercase values override camelCase ones.

**Comment by break-stuff** [comment]
Are these intended to be properties or attributes? 

It is assuming these are attributes because of the current configuration, but, as you have seen, attributes don't respect camel-case.

You will need to update your code to either map to attributes:

```
@property({ type: Boolean, attribute: 'disabled' }) 
isDisabled: boolean = false; 

@property({ type: Boolean, attribute: 'loading' }) 
isLoading: boolean = false;
```

Or to be property-only:

```
@property({ type: Boolean, attribute: false }) 
isDisabled: boolean = false; 

@property({ type: Boolean, attribute: false }) 
isLoading: boolean = false;
```

**Comment by nikita-rudenko** [comment]
Thanks for clarification!
In my case it makes the most sense to just rename properties to `loading` and `disabled` and keep them as attributes.
