### ISSUE TITLE
Incompatible with Storybook 8.0.6

### ISSUE THREAD

**Issue by dgibson666** [break-stuff/wc-storybook-helpers#70]
After upgrading Storybook to the latest v8.06, I get the following warnings in the CLI:

WARN The following packages are incompatible with Storybook 8.0.6 as they depend on different major versions of Storybook packages:
WARN - wc-storybook-helpers@2.0.1
WARN  Repo: https://github.com/break-stuff/wc-storybook-helpers#readme

**Comment by CollinHerber** [comment]
I am also experiencing this on 8.0.8

**Comment by break-stuff** [comment]
Thank you for letting me know! This is likely because we also support v7 APIs, but we should be able to fix this.

**Comment by break-stuff** [comment]
This should now be fixed in release 2.0.2

**Comment by break-stuff** [comment]
Closing for now. Let me know if you run into any issues.

**Comment by CollinHerber** [comment]
![Screenshot 2024-05-21 at 2 36 46 PM](https://github.com/break-stuff/wc-storybook-helpers/assets/24656209/b01779a0-128a-43ea-a7c4-c98a9ae1a021)

Got around to trying out the latest but getting the following

Here is my full story

import { Meta, StoryObj } from '@storybook/web-components';
import './scoped-notification.slds';
import { NjcSldsScopedNotification } from './scoped-notification.slds';
import { getWcStorybookHelpers } from 'wc-storybook-helpers';
const { events, args, argTypes, template } =
    getWcStorybookHelpers('nsc-scoped-notification');

const meta: Meta<NjcSldsScopedNotification> = {
    title: 'Components/ScopedNotification/Slds',
    component: 'nsc-scoped-notification',
    args,
    argTypes,
    parameters: {
        actions: {
            handles: events,
        },
    },
};
export default meta;

type Story = StoryObj<NjcSldsScopedNotification & {slotContent: string}>;
export const Example: Story = {
    render: (args) => template(args),
    args: {
        slotContent: 'Slot',
        theme: 'success',
    },
};
