### ISSUE TITLE
Question regarding slotted content examples

### ISSUE THREAD

**Issue by JamesIves** [break-stuff/wc-storybook-helpers#77]
This is more of a question than anything- but what is the intended way to default slot content in the slots section of the addons control? I know you can pass slotted content as the second arg of the `template` method, but it results in the content being uneditable, any additions made in the addons panel ends up duplicating any named slots placed there as opposed to replacing it, likewise there's no way to edit the default slot, only slots with a name.

I was able to default named slots like so, which makes it so the string is editable, and it seems to work pretty well (slot name is `image`, so you can target `image-slot` as an arg):

```js
export const LargeWithIcon: Story = {
  args: {
    size: 'large',
    'image-slot': `<img
      src="..."
      alt=""
      slot="image"
    />`,
  },
};
```

However the usage of Lit's `html` method doesn't work here, meaning it has to be passed as a string. This feels bad because you end up losing a fair amount of tooling that comes with it.

```js
export const LargeWithIcon: Story = {
  args: {
    size: 'large',
    'image-slot': html`<img
      src="..."
      alt=""
      slot="image"
    />`, // Results in [object,Object] showing in the storybook preview
  },
};
```

Feels like this piece is fairly undocumented as I couldn't find a specific callout on how to do this in the docs. Would love to see support for more default slot configuration as for less atomic components they need to be staged almost entirely with slots to make sense to library users. 

Can't stress enough how useful this library continues to be ❤️

**Comment by JamesIves** [comment]
Ah, looks like the following works with a `default-slot` arg when you have the following in JSDoc:

```
@slot default - A slot for default content.
```

**Comment by break-stuff** [comment]
Yes, it is intended. The `args` content is rendered in a textbox, and lit's tagged templates are actually functions. Users updating the slotted content from storybook have to do it by manipulating the value in the controls textbox (which is a string).

You should also be able to use `default-slot` with an unnamed slot as well.

```
@slot A slot for default content.
```
