### ISSUE TITLE
Dropdown for variant 

### ISSUE THREAD

**Issue by herrKlein** [break-stuff/wc-storybook-helpers#84]
In my project I could not get a dropdown working for this
```ts
  @property({ type: String })
  public orientation:  'horizontal' | 'vertical' | undefined;
```
or 
```ts
  export type Orientation = 'horizontal' | 'vertical' | undefined;

  @property({ type: String })
  public orientation: Orientation;
```

So I copied your example in our project, and let the manifest run through that, 
but also does not create a dropdown.
<img width="646" alt="Screenshot 2024-12-04 at 12 21 30" src="https://github.com/user-attachments/assets/79d03586-98d8-4a03-b76d-08add5e6733a">

Is it broken, or am I missing something

**Comment by herrKlein** [comment]
My bad, 

I did forget to add this plugin to the manifest

    expandTypesPlugin()

and this in the preview.ts

setWcStorybookHelpersConfig({
  hideArgRef: false,
  typeRef: 'expandedType',
  renderDefaultValues: false
});

now it works

**Comment by break-stuff** [comment]
For this scenario, you will need something like the expanded types plugin to create a type that can be parsed.

https://www.npmjs.com/package/cem-plugin-expanded-types

**Comment by herrKlein** [comment]
Do you know how to hide private, protected members without breaking this plugin. I filter them out now in the manifest. There is no need to have private and protected members in storybook I think?

**Comment by break-stuff** [comment]
Are they flagged at private/protected in the manifest? It should do that already.

**Comment by herrKlein** [comment]
You are right, it was an issue on my side. I started the property with an underscore _maxChoices. But because I have a decorator on this property I needed it to be public. However the _ made it seem it should be private
